apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: database-volume
  name: database-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
