apiVersion: v1
kind: Service
metadata:
  labels:
    service: server-app
  name: server-app
spec:
  selector:
    service: server-app
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
      nodePort: 30012
      name: http
  type: NodePort

